title: Marco Capano
email: marco24capano@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, it's Marco!ğŸ‘¨ğŸ»â€ğŸ’» I build iOS apps ğŸ, contribute to open source and study Computer Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcocapano1
github_username:  marcocapano

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
google_analytics: UA-133490817-2
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
